import type { Metadata } from "next";
import { PitchShell, PitchButton, SectionHeading } from "@/components/pitch-shell";
import { DEMO_VIDEO_URL, demoChapters, pitchConfig } from "@/lib/pitch-config";
import { resolveDemoVideo } from "@/lib/demo-video";

export const metadata: Metadata = { title: "Demo | TrackBus AI", description: "A judge’s guide to TrackBus: anonymous counting, occupancy, forecasting and a working transport intelligence prototype." };

export default function Demo() {
  const video = resolveDemoVideo(DEMO_VIDEO_URL);
  return <PitchShell active="demo"><div className="pitch-container">
    <section className="pitch-page-hero"><span className="pitch-status"><i />{pitchConfig.status}</span><div className="pitch-eyebrow">AIFU PITCH DAY 3.0 / DEMO</div><h1>TrackBus <em>Demo</em></h1><p>Follow a passenger-flow signal from the bus doorway to an operator’s decision—and a passenger’s screen.</p></section>
    <section className="pitch-video-section" aria-label="Demo video"><div className="pitch-video-frame">{video?.kind === "embed" ? <iframe src={video.url} title="TrackBus AI demo video" allow="fullscreen; picture-in-picture; encrypted-media" allowFullScreen loading="lazy" referrerPolicy="strict-origin-when-cross-origin" /> : video?.kind === "video" ? <video controls preload="metadata" playsInline aria-label="TrackBus AI demo video"><source src={video.url} type={video.url.split("?")[0].endsWith(".webm") ? "video/webm" : "video/mp4"} /><p>Your browser cannot play this video. <a href={video.url}>Open the demo video</a>.</p></video> : <div className="pitch-video-placeholder"><span className="pitch-play-symbol" aria-hidden="true"><svg width="32" height="32" viewBox="0 0 24 24" fill="none"><path d="m9 5 11 7-11 7V5Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/></svg></span><span className="pitch-eyebrow">1–5 MINUTE PRODUCT WALKTHROUGH</span><h2>Demo video coming soon</h2><p>The working prototype is ready to explore below.</p><PitchButton href={pitchConfig.prototypeUrl}>Open Working Prototype</PitchButton></div>}</div><div className="pitch-video-caption"><span>Vision → events → occupancy → forecast → decisions</span><span>{video ? "Product walkthrough" : "Recording to be added before submission"}</span></div></section>
    <section className="pitch-section"><SectionHeading number="01" eyebrow="THE WALKTHROUGH" title="What you will see">The planned 1–5 minute walkthrough explains the full flow. The platform’s synthetic scenario demonstrates decision-making; the Vision tools demonstrate detection, tracking and event creation.</SectionHeading><ol className="pitch-demo-chapters">{demoChapters.map(([title, description], index) => <li key={title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{title}</h3><p>{description}</p></div></li>)}</ol></section>
    <section className="pitch-demo-resources"><div><span className="pitch-eyebrow">EXPLORE THE WORKING SOFTWARE</span><h2>Go from the pitch to the product.</h2><p>The existing operator dashboard, passenger beta, API and scenario controls are available in the prototype. Use the “TrackBus pitch” link to return here.</p></div><div className="pitch-actions"><PitchButton href={pitchConfig.prototypeUrl}>Open Working Prototype</PitchButton><PitchButton href={pitchConfig.repositoryUrl} secondary external>View Source Code</PitchButton><PitchButton href={pitchConfig.guideUrl} secondary external>Read Technical Guide</PitchButton><PitchButton href="/developers" secondary>View API</PitchButton></div></section>
    <aside className="pitch-validation-note"><span>VALIDATION STATUS</span><p>This demo represents an MVP/research prototype. Production counting accuracy has not yet been validated on representative Tashkent fleet footage. Showcase fleet values, intervention effects and confidence figures are illustrative; the Live Pilot view reads stored events when a source is connected.</p></aside>
  </div></PitchShell>;
}
