/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: cb0b978148263e6af11144d7e28e1bfd)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	TRACKBUS_INGEST_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
