import Link from "next/link";
import { PitchShell, PitchButton, SectionHeading, Arrow } from "@/components/pitch-shell";
import { FleetPreview, SignalPipeline } from "@/components/pitch-interactions";
import { pitchConfig, implementation, roadmap } from "@/lib/pitch-config";
import { route22Buses } from "@/lib/sample-data";
import { occupancyPercent } from "@/lib/contracts";

const features = [
  { number: "01", title: "Live occupancy", body: "See estimated bus loads and the quality of the signal behind them.", view: "command" },
  { number: "02", title: "Passenger flow", body: "Inspect boarding and alighting events across stops and source feeds.", view: "pilot" },
  { number: "03", title: "Demand forecast", body: "Explore future crowding with a transparent, testable baseline.", view: "forecast" },
  { number: "04", title: "Operator intelligence", body: "Investigate capacity imbalance and review possible interventions.", view: "command" },
  { number: "05", title: "Passenger experience", body: "Simple crowding bands for the bus now and at an approaching stop.", view: "passenger" },
  { number: "06", title: "TrackBus Vision", body: "YOLO detection and ByteTrack temporary tracking produce count events.", view: "system" },
];
const evidence = [
  ["Vision pipeline", "Detection, tracking & directional counting", "trackbus"],
  ["Operator + passenger UI", "Working dashboard & passenger beta", "components"],
  ["Canonical API", "Event contracts & offline delivery queue", "contracts"],
  ["Forecast baseline", "Transparent occupancy model", "lib/forecast.ts"],
  ["Evaluation framework", "Ground-truth tools & failure diagnostics", "docs/evaluation.md"],
  ["Deployment foundation", "Workers, D1 & documented safeguards", "docs/cloudflare-deployment.md"],
];

export default function Home() {
  return <PitchShell active="home">
    <section className="pitch-hero pitch-container">
      <div className="pitch-hero-copy"><div className="pitch-status"><i />{pitchConfig.status}</div><p className="pitch-hero-kicker">TRANSPORT INTELLIGENCE / TRACKBUS AI</p><h1>Turn passenger flow into <em>better transport decisions.</em></h1><p className="pitch-hero-description">Anonymous passenger-flow data, existing transport infrastructure and AI forecasting. One clearer view of crowding, demand and fleet imbalance.</p><div className="pitch-actions"><PitchButton href={pitchConfig.prototypeUrl}>Open Live Demo</PitchButton><PitchButton href="#how-it-works" secondary>See how it works</PitchButton></div><Link className="pitch-text-link pitch-video-link" href="/demo"><span aria-hidden="true">▷</span> View Demo Video</Link><div className="pitch-hero-footnote"><span className="pitch-tiny-line" />Working software foundation. Next: representative validation and a controlled pilot.</div></div>
      <div className="pitch-hero-product"><FleetPreview /><div className="pitch-product-caption"><span>ANONYMOUS SIGNALS → ACTIONABLE INSIGHT</span><span>Built on the existing TrackBus prototype</span></div></div>
    </section>

    <div className="pitch-principles"><div className="pitch-container"><span><i />Multiple data sources</span><span><i />Anonymous by design</span><span><i />Forecasts operators can inspect</span><span><i />Decisions stay with people</span></div></div>

    <section className="pitch-section pitch-container" id="problem">
      <div className="pitch-two-column"><SectionHeading number="01" eyebrow="THE PROBLEM" title="Same route. Uneven pressure.">One bus is crowded. Another has room. Fragmented signals make the imbalance hard to see—and harder to act on.</SectionHeading><div className="pitch-capacity-comparison"><span className="pitch-eyebrow">FROM THE SYNTHETIC ROUTE 22 SCENARIO</span>{[route22Buses[3], route22Buses[1]].map(bus => <div key={bus.id} className="pitch-capacity-row"><div><strong>Bus {bus.label}</strong><span>{bus.occupancy >= 60 ? "Crowding pressure" : "Available capacity"}</span></div><div className="pitch-capacity-track"><i style={{ width: `${occupancyPercent(bus.occupancy, bus.capacity)}%`, background: bus.occupancy >= 60 ? "var(--coral)" : "var(--mint)" }} /></div><strong>{occupancyPercent(bus.occupancy, bus.capacity)}%</strong></div>)}<small>Illustrative bus loads, not measured fleet performance.</small></div></div>
      <div className="pitch-problem-grid"><article><span>01 / FRAGMENTED</span><h3>Data exists.<br />The picture is incomplete.</h3><p>CCTV, GPS, APC and operational records can sit in separate systems.</p></article><article><span>02 / REACTIVE</span><h3>Crowding appears<br />before the response.</h3><p>Operators need a way to spot recurring pressure and underused capacity.</p></article><article><span>03 / UNCERTAIN</span><h3>A bus is coming.<br />Will there be room?</h3><p>Passengers need crowding information for when the bus reaches their stop.</p></article></div>
    </section>

    <section className="pitch-section pitch-solution" id="how-it-works"><div className="pitch-container"><SectionHeading number="02" eyebrow="THE SOLUTION" title="From scattered signals to a shared operating picture.">TrackBus turns anonymous passenger events into occupancy visibility, demand forecasts and decisions worth investigating.</SectionHeading><SignalPipeline /><div className="pitch-source-note"><span>Source strategy</span><p>Approved APC first where available. Existing CCTV, optional TrackBus Vision, GPS and historical operations add context. Payment or demand data is a future pathway where legally and technically available.</p></div></div></section>

    <section className="pitch-section pitch-container" id="product"><div className="pitch-section-row"><SectionHeading number="03" eyebrow="THE PRODUCT" title="One signal. Two perspectives.">A detailed workspace for operators. A simple crowding picture for passengers.</SectionHeading><PitchButton href={pitchConfig.prototypeUrl} secondary>Explore the platform</PitchButton></div><div className="pitch-feature-grid">{features.map(feature => <Link className="pitch-feature" key={feature.title} href={`/platform?view=${feature.view}`}><div><span>{feature.number}</span><Arrow diagonal /></div><h3>{feature.title}</h3><p>{feature.body}</p><span className="pitch-feature-link">Open in working prototype →</span></Link>)}</div><div className="pitch-privacy-strip"><svg width="32" height="32" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z" stroke="currentColor" strokeWidth="1.5"/><path d="m8 12 3 3 5-6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></svg><div><h3>Passenger intelligence without passenger identities.</h3><p>No facial recognition. No persistent identity tracking. Temporary tracks, anonymous counts, operator-approved decisions.</p></div><a href={`${pitchConfig.repositoryUrl}/blob/pitch-day-3.0/docs/privacy-and-safety.md`} target="_blank" rel="noopener noreferrer">Read the privacy approach ↗</a></div></section>

    <section className="pitch-section pitch-evidence-section" id="why-us"><div className="pitch-container"><div className="pitch-two-column"><SectionHeading number="04" eyebrow="WHY WE CAN BUILD THIS" title="Already beyond the idea stage.">The path from detection to a working interface is in the repository. The next challenge is proving reliability on representative data.</SectionHeading><div className="pitch-evidence-path"><span className="done">Idea <b>✓</b></span><i /><span className="done">Code <b>✓</b></span><i /><span className="current">Working prototype</span><i /><span>Pilot</span></div></div><div className="pitch-evidence-grid">{evidence.map(([title, description, path]) => <a href={`${pitchConfig.repositoryUrl}/tree/pitch-day-3.0/${path}`} key={title} target="_blank" rel="noopener noreferrer"><span className="pitch-evidence-check">✓</span><div><h3>{title}</h3><p>{description}</p></div><Arrow diagonal /></a>)}</div><p className="pitch-honesty-note">Software evidence is not production validation. No completed live pilot, customer deployment, official transport integration or validated production accuracy is claimed.</p></div></section>

    <section className="pitch-section pitch-container" id="roadmap"><SectionHeading number="05" eyebrow="THE ROADMAP" title="Build. Validate. Then scale.">MVP is the current stage. A controlled pilot is the next gate.</SectionHeading><div className="pitch-roadmap">{roadmap.map((stage, index) => <article className={index === 2 ? "current" : index < 2 ? "complete" : ""} key={stage.name}><div className="pitch-roadmap-marker">{index < 2 ? "✓" : String(index + 1).padStart(2, "0")}</div><span className="pitch-roadmap-state">{stage.state}</span><h3>{stage.name}</h3><p>{stage.description}</p><ul>{stage.items.map(item => <li key={item}>{item}</li>)}</ul></article>)}</div></section>

    <section className="pitch-section pitch-build-section" id="implementation"><div className="pitch-container"><SectionHeading number="06" eyebrow="IMPLEMENTATION PLAN" title="A practical route to real-world evidence.">Validate the signal, measure the infrastructure and improve the operator workflow before adding vehicles.</SectionHeading><div className="pitch-build-grid">{implementation.map((stage, index) => <article key={stage.title}><span className="pitch-build-number">{String(index + 1).padStart(2, "0")}</span><div><h3>{stage.title}</h3><p>{stage.body}</p><small>{stage.tools}</small></div></article>)}</div><div className="pitch-architecture"><div><span className="pitch-eyebrow">ARCHITECTURE DECISION</span><h3>Measure before choosing where inference runs.</h3><p>The pilot will compare network availability, latency, compute performance and cost. Workers receives lightweight events; the vision model runs on appropriate edge or server hardware.</p></div><div className="pitch-architecture-paths"><div><span>EDGE PATH</span><p>Camera <b>→</b> Edge compute <b>→</b> JSON event <b>→</b> API</p></div><div><span>SERVER PATH</span><p>Camera <b>→</b> Network <b>→</b> Server inference <b>→</b> Event</p></div></div></div><div className="pitch-ai-grid"><article><span className="pitch-eyebrow">AI / COMPUTER VISION</span><h3>Detect people. Understand direction.</h3><p>YOLO detects people. ByteTrack maintains temporary tracks. Trajectory analysis and directional crossing logic generate boarding and alighting events.</p></article><article><span className="pitch-eyebrow">AI / FORECASTING</span><h3>A baseline we can test and improve.</h3><p>Today: weighted recent occupancy and explicit context factors, with heuristic confidence. Next: train and evaluate forecasting models on real historical operations.</p></article><article><span className="pitch-eyebrow">DEVELOPMENT TOOLS</span><h3>AI helps us build the software.</h3><p>AI-assisted coding, experiment analysis, automated testing and documentation support development. They are separate from the product’s computer vision and forecasting.</p></article></div></div></section>

    <section className="pitch-section pitch-container" id="team"><SectionHeading number="07" eyebrow="THE TEAM" title="Built close to the whole system.">Product, vision, APIs and interfaces connect in one working software foundation.</SectionHeading><div className="pitch-team-grid">{pitchConfig.team.map(member => <article className="pitch-team-card" key={member.name}><div className="pitch-team-person"><span className="pitch-avatar">{member.initials}</span><div><h3>{member.name}</h3><span>{member.role}</span></div>{member.links.map(link => <a key={link.href} href={link.href} aria-label={`${member.name} on ${link.label}`} target="_blank" rel="noopener noreferrer"><Arrow diagonal /></a>)}</div><p>{member.description}</p><h4>Responsibilities</h4><div className="pitch-tags">{member.responsibilities.map(item => <span key={item}>{item}</span>)}</div><h4>Skills & tools</h4><div className="pitch-tags pitch-skill-tags">{member.skills.map(item => <span key={item}>{item}</span>)}</div></article>)}<div className="pitch-team-stack"><span className="pitch-eyebrow">THE TECHNOLOGY FOUNDATION</span><h3>From a doorway event<br />to an operator’s screen.</h3><div className="pitch-tech-list">{pitchConfig.technologies.map(item => <span key={item}>{item}</span>)}</div><div className="pitch-team-links"><a href={pitchConfig.repositoryUrl} target="_blank" rel="noopener noreferrer">Source code ↗</a><a href={pitchConfig.documentationUrl} target="_blank" rel="noopener noreferrer">Technical documentation ↗</a><a href={pitchConfig.guideUrl}>Technical guide ↗</a><Link href={pitchConfig.prototypeUrl}>Live demo ↗</Link></div></div></div></section>

    <section className="pitch-final-cta pitch-container"><div><span className="pitch-eyebrow">WORKING MVP / NEXT: A CONTROLLED PILOT</span><h2>See the signal.<br /><em>Explore the decisions.</em></h2><p>Open the existing prototype, inspect the pipeline and explore the passenger experience.</p></div><div><PitchButton href={pitchConfig.prototypeUrl}>Open Live Demo</PitchButton><PitchButton href="/demo" secondary>View Demo Video</PitchButton><Link className="pitch-text-link" href="/ask">Questions? Ask TrackBus →</Link></div></section>
  </PitchShell>;
}
