import type { Metadata } from "next";
import { PitchShell, PitchButton, SectionHeading } from "@/components/pitch-shell";
import { CopyCode } from "@/components/pitch-interactions";
import { apiEndpoints, examplePassengerEvent } from "@/lib/pitch-api";
import { pitchConfig } from "@/lib/pitch-config";

export const metadata: Metadata = { title: "API & Developers | TrackBus AI", description: "Inspect the TrackBus passenger-count contract, hosted API endpoints, authenticated ingestion and transparent baseline forecast." };

export default function Developers() {
  const event = JSON.stringify(examplePassengerEvent, null, 2);
  const forecast = JSON.stringify({ recentOccupancy: [42, 47, 51, 56, 61, 66], capacity: 72, hour: 19, dayType: "weekday", weather: "clear", eventNearby: false }, null, 2);
  const request = `curl '${pitchConfig.siteUrl}/api/v1/events/passenger-counts' \\\n  -X POST \\\n  -H 'Content-Type: application/json' \\\n  -H 'Authorization: Bearer <YOUR_DEVICE_KEY>' \\\n  --data '${event}'`;
  return <PitchShell active="developers"><div className="pitch-container">
    <section className="pitch-page-hero"><span className="pitch-status"><i />{pitchConfig.status}</span><div className="pitch-eyebrow">DEVELOPERS / REAL ROUTES, INSPECTABLE CONTRACTS</div><h1>One contract.<br /><em>Many signal sources.</em></h1><p>TrackBus Passenger Count Event API. Anonymous counts, operational context and quality flags connect the vision pipeline to transport intelligence.</p><div className="pitch-actions"><PitchButton href="/api/v1/health" secondary>Inspect gateway health</PitchButton><PitchButton href={pitchConfig.documentationUrl} secondary external>Read documentation</PitchButton></div></section>
    <section className="pitch-api-section"><SectionHeading number="01" eyebrow="HOSTED API" title="Explore the gateway">These are the existing web routes. Public reads are safe to inspect; ingestion requires a configured device key and D1 storage.</SectionHeading><div className="pitch-endpoint-list">{apiEndpoints.map(endpoint => <article key={`${endpoint.method}${endpoint.path}`}><div><span className={`pitch-method ${endpoint.method.toLowerCase()}`}>{endpoint.method}</span><code>{endpoint.path}</code>{endpoint.publicUrl && <a href={endpoint.publicUrl} target="_blank" rel="noopener noreferrer" aria-label={`Open ${endpoint.title} JSON`}>Open JSON ↗</a>}</div><h3>{endpoint.title}</h3><p>{endpoint.detail}</p></article>)}</div></section>
    <section className="pitch-section"><SectionHeading number="02" eyebrow="CANONICAL EVENT / SCHEMA 1.0" title="Small payload. Useful context.">The real contract uses busId, not vehicleId. Confidence is source metadata, not independently validated accuracy. This example is synthetic.</SectionHeading><div className="pitch-code-grid"><CopyCode code={event} label="passenger-count-event.json" /><div className="pitch-contract-notes"><h3>Built for auditable delivery</h3><dl><dt>Idempotency</dt><dd>eventId identifies an event across retries. Repeated delivery does not add a second row.</dd><dt>Authentication</dt><dd>The device bearer key stays outside the browser and source control. This page contains a placeholder only.</dd><dt>Quality</dt><dd>observedAt, source, confidence and qualityFlags help explain the signal and its freshness.</dd><dt>Privacy</dt><dd>No faces, frames or persistent passenger IDs are part of the event contract.</dd></dl><a href={`${pitchConfig.repositoryUrl}/blob/pitch-day-3.0/contracts/passenger-count-event.schema.json`} target="_blank" rel="noopener noreferrer">Inspect the JSON schema ↗</a></div></div><CopyCode code={request} label="Authenticated ingestion example" /><p className="pitch-honesty-note">Run an ingestion example only against an approved test target with your device key. This showcase page does not send events.</p></section>
    <section className="pitch-section pitch-forecast-docs"><SectionHeading number="03" eyebrow="FORECAST BASELINE" title="Transparent before it is sophisticated.">POST this input to /api/v1/forecast. The baseline weights recent occupancy and applies explicit context factors. Confidence and ranges are heuristic, pending evaluation.</SectionHeading><CopyCode code={forecast} label="forecast-input.json" /><PitchButton href="/platform?view=forecast">Open Forecast Lab</PitchButton></section>
  </div></PitchShell>;
}
